app/models/link.py
from app.extensions import db
from datetime import datetime


class Link(db.Model):
    __tablename__ = 'links'

    id = db.Column(db.Integer, primary_key=True)
    personal_info = db.relationship('PersonalInfo', uselist=False, backref='link')
    token = db.Column(db.String(255), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

app/models/personal_info.py
from app.extensions import db
from datetime import datetime


class PersonalInfo(db.Model):
    __tablename__ = 'personal_infos'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    link_id = db.Column(db.Integer, db.ForeignKey('links.id'), nullable=False)
    product_title = db.Column(db.String(64), nullable=False)
    name = db.Column(db.String(64), nullable=False)
    contact_name = db.Column(db.String(64), nullable=False)
    contact_phone = db.Column(db.String(64), nullable=False)
    extra_contact_name = db.Column(db.String(64))
    extra_contact_phone = db.Column(db.String(64))
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

app/models/user.py
from app.extensions import db
from datetime import datetime


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    personal_infos = db.relationship('PersonalInfo', backref='user', lazy='dynamic')
    email = db.Column(db.String(64), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    name = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

app/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 64)])
    submit = SubmitField('Login')

app/forms/personal_info_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email


class PersonalInfoForm(FlaskForm):
    product_title = StringField('Product Title', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    contact_name = StringField('Contact Name', validators=[DataRequired()])
    contact_phone = StringField('Contact Phone', validators=[DataRequired()])
    extra_contact_name = StringField('Extra Contact Name')
    extra_contact_phone = StringField('Extra Contact Phone')
    description = TextAreaField('Description')
    submit = SubmitField('Save')

app/forms/signup_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class SignupForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    name = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 64)])
    submit = SubmitField('Sign Up')

app/__init__.py
import os

from flask import Flask
from flask_wtf import CSRFProtect
from config import Config
from app.personal_info import personal_blueprint
from app.auth import auth_blueprint
from app.products import products_blueprint
from app.extensions import db, migrate, csrf


def create_app(config_class=Config):
    app = Flask(__name__)

    # if app.config['FLASK_ENV'] == 'development':
    from dotenv import load_dotenv
    load_dotenv()

    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
    # app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app)
    csrf.init_app(app)

    app.register_blueprint(personal_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(products_blueprint)

    return app

app/personal_info/__init__.py
from flask import Blueprint

personal_blueprint = Blueprint('personal_info', __name__)

from app.personal_info import routes

app/personal_info/routes.py
from flask import render_template, request, redirect, url_for, jsonify

from app.auth.decorators import login_required
from app.auth.helpers import get_current_user, is_link_authorized
from app.forms.personal_info_form import PersonalInfoForm
from app.models.link import Link
from app.models.personal_info import PersonalInfo
from app.extensions import db
from app.personal_info import personal_blueprint


@personal_blueprint.route('/info/<token>/details')
def personal_info_details(token):
    link = Link.query.filter_by(token=token).first()
    if not link:
        return render_template('link_not_found.html')
    current_user = get_current_user()
    return render_template('personal_info/details.html', token=token, link=link,
                           current_user=current_user, personal_info=link.personal_info)


@personal_blueprint.route('/info/<token>/edit')
@login_required
def personal_info_edit(token):
    link = Link.query.filter_by(token=token).first()
    form = PersonalInfoForm(obj=link.personal_info)
    current_user = get_current_user()

    if link.personal_info and not (link.personal_info.user == current_user):
        return redirect(url_for('personal_info.personal_info_details', token=token))

    return render_template('personal_info/edit.html', token=token, form=form, current_user=current_user)


@personal_blueprint.route('/info/<token>/edit', methods=['POST'])
@login_required
def personal_info_post(token):
    form = PersonalInfoForm(request.form)

    if not form.validate():
        return render_template('personal_info/personal_info_edit.html', token=token, form=form)

    link = Link.query.filter_by(token=token).first()
    current_user = get_current_user()

    if not is_link_authorized(link, current_user):
        return jsonify({'error': 'not authorized'}), 401

    personal_info = link.personal_info or PersonalInfo()

    form.populate_obj(personal_info)

    if not personal_info.user:
        personal_info.user = current_user
    if not personal_info.link:
        personal_info.link = link

    db.session.add(personal_info)
    db.session.commit()

    return redirect(url_for('personal_info.personal_info_details', token=token))


@personal_blueprint.route('/info/<token>/delete', methods=['POST'])
@login_required
def personal_info_delete(token):
    link = Link.query.filter_by(token=token).first()
    current_user = get_current_user()

    if not is_link_authorized(link, current_user):
        return jsonify({'error': 'not authorized'}), 401

    db.session.delete(link.personal_info)
    db.session.commit()

    return redirect(url_for('products.list'))

app/products/__init__.py
from flask import Blueprint

products_blueprint = Blueprint('products', __name__)

from app.products import routes

app/products/routes.py
from flask import render_template

from app.extensions import db
from app.auth.decorators import login_required
from app.auth.helpers import get_current_user
from app.models.link import Link
from app.models.personal_info import PersonalInfo
from app.products import products_blueprint


@products_blueprint.route('/products')
@login_required
def list():
    current_user = get_current_user()
    personal_infos = (PersonalInfo.query.join(Link).options(db.joinedload(PersonalInfo.link)).
                      filter(PersonalInfo.user_id == current_user.id).all())
    return render_template('products/list.html', current_user=current_user, personal_infos=personal_infos)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <script src="{{ url_for('static', filename='js/delete_modal.js') }}"></script>
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu is-active">
                        <div class="start">
                            {% if current_user %}
                                <a href="{{ url_for('products.list') }}" class="navbar-item navbar-text">
                                    Products
                                </a>
                            {% endif %}
                        </div>
                        <div class="navbar-end">
                            {% if not current_user and token  %}
                                <a href="{{ url_for('auth.login', token=token) }}" class="navbar-item navbar-text">
                                    Login
                                </a>
                            {% elif current_user %}
                                <div class="navbar-item navbar-text">{{current_user.name}}</div>
                                <a href="{{url_for('auth.logout', token=token) if token else url_for('auth.logout_without_token')}}" class="navbar-item navbar-text">
                                    Logout
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>

</html>

app/templates/link_not_found.html
{% extends "/base.html" %}
{% from "partials/_render_field.html" import render_field %}

{% block content %}
<div class="column is-4 is-offset-4">
    <article class="message is-danger">
      <div class="message-header">
        <p>Link not found</p>
      </div>
      <div class="message-body">
        <strong>The link doesn't exist. Please, scan it.<p>Do not enter it manually.</p></strong>
      </div>
    </article>
</div>
{% endblock %}

app/templates/partials/_render_field.html
{% macro render_field(field) %}
    <div class="field">
        <div class="control">
            {{field(**kwargs)|safe}}
              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="help is-danger">{{error}}</p>
                {% endfor %}
              {% endif %}
        </div>
    </div>
{% endmacro %}

app/templates/partials/_render_labeled_field.html
{% macro render_labeled_field(field) %}
    <div class="field">
        {{field.label(class="label", style="color:hsl(0, 0%, 48%)")}}
        <div class="control">
            {{field(**kwargs)|safe}}
              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="help is-danger">{{error}}</p>
                {% endfor %}
              {% endif %}
        </div>
    </div>
{% endmacro %}

app/templates/personal_info/details.html
{% extends "/base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    {% if current_user == personal_info.user %}
        <div class="edit-button">
            <a href="{{ url_for('personal_info.personal_info_edit', token=token) }}" class="button is-primary is-large is-pulled-right">
               <b>Edit</b>
            </a>
        </div>
    {% endif %}
    <div class="box">
        <div class="image-container">
            <img class="avatar-image" src="{{ url_for('static', filename='images/avatar.jpg') }}" alt="My Image">
            <div class="avatar-text-overlay">
                <h1 class="avatar-title-italic"><em>Hello,</em></h1>
                <h2 class="avatar-subtitle">My name is <b>{{personal_info.name}}</b></h2>
            </div>
        </div>

        <p class="avatar-title-italic" >Please,</p>
        <p class="avatar-subtitle" >CALL MY PARENTS:</p>
        <br>

        <div class="box contact-person-box">
            {{personal_info.contact_phone}} {{personal_info.contact_name}}
        </div>

        {% if personal_info.extra_contact_phone %}
            <div class="box contact-person-box">
                {{personal_info.extra_contact_phone}} {{personal_info.extra_contact_name}}
            </div>
        {% endif %}

        {% if personal_info.description %}
            <div class="box">
                {{personal_info.description}}
            </div>
        {% endif %}

        <p class="footer-text" >Thank you!</p>
    </div>
</div>
{% endblock %}

app/templates/personal_info/edit.html
{% extends "/base.html" %}
{% from "partials/_render_field.html" import render_field %}
{% from "partials/_render_labeled_field.html" import render_labeled_field %}

{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        <form method="POST" action="{{ url_for('personal_info.personal_info_post', token=token) }}">
            {{ form.csrf_token }}

            {{ render_labeled_field(form.product_title, class="input is-large" + (" is-danger" if form.product_title.errors else ""), autofocus="") }}
            {{ render_labeled_field(form.name, class="input is-large" + (" is-danger" if form.name.errors else "")) }}
            {{ render_labeled_field(form.contact_name, class="input is-large" + (" is-danger" if form.contact_name.errors else "")) }}
            {{ render_labeled_field(form.contact_phone, class="input is-large" + (" is-danger" if form.contact_phone.errors else "")) }}
            {{ render_labeled_field(form.extra_contact_name, class="input is-large" + (" is-danger" if form.extra_contact_name.errors else "")) }}
            {{ render_labeled_field(form.extra_contact_phone, class="input is-large" + (" is-danger" if form.extra_contact_phone.errors else "")) }}
            {{ render_labeled_field(form.description, rows="5", class="textarea is-large" + (" is-danger" if form.description.errors else "")) }}

            {{ form.submit(class="button is-block is-info is-large is-fullwidth", value=form.submit.label.text) }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/products/list.html
{% extends "/base.html" %}

{% block content %}
<div class="column is-7 is-offset-2">
    <article class="panel products-panel">
      <p class="panel-heading products-panel-heading">
        Products
      </p>
        {% for personal_info in personal_infos %}
          <div class="panel-block products-panel-block">
            <p class="control has-icons-right">
              <a class="products-panel-link" href="{{ url_for('personal_info.personal_info_details', token=personal_info.link.token) }}">
                {{personal_info.product_title}}
              </a>

              <span class="icon is-right products-panel-delete">
                  <div id="modal-{{personal_info.link.token}}" class="modal">
                    <div class="modal-background"></div>
                    <div class="modal-card">
                      <header class="modal-card-head">
                        <p class="modal-card-title">Delete {{personal_info.product_title}}</p>
                        <button class="delete" aria-label="close"></button>
                      </header>
                      <section class="modal-card-body">
                        Do you want to delete {{personal_info.product_title}} product ?
                        </br>
                        The associated info will be wiped out. And the product will be removed from the list.
                      </section>
                      <footer class="modal-card-foot">
                        <form method="post" class="action-form-button" action="{{ url_for('personal_info.personal_info_delete', token=personal_info.link.token) }}">
                          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                          <button class="button is-danger">Delete</button>
                        </form>

                        <button class="button">Cancel</button>
                      </footer>
                    </div>
                  </div>

                  <button class="delete products-panel-delete-button is-large js-modal-trigger" data-target="modal-{{personal_info.link.token}}" title="Delete product's data and remove it from the list"></button>
              </span>
            </p>
          </div>
        {% endfor %}

        {% if not personal_infos %}
          <div class="panel-block products-panel-block">
            There is no products.
          </div>
        {% endif %}
    </article>
</div>
{% endblock %}